# Site settings
title: OpenStreetMap India
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  OpenStreetMap India
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openstreetmap.in"
twitter_username: openstreetmapIN
github_username:  osm-in

# Build settings
markdown: kramdown
